//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormUI.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormUI.Util.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je zauzet!.
        /// </summary>
        internal static string email_con {
            get {
                return ResourceManager.GetString("email_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je obavezno polje!.
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email nije u ispravnom formatu!.
        /// </summary>
        internal static string emailRegex_err {
            get {
                return ResourceManager.GetString("emailRegex_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno polje!.
        /// </summary>
        internal static string fname_req {
            get {
                return ResourceManager.GetString("fname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacija.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće kreirati trgovinu bez kreiranja korisničkog naloga!.
        /// </summary>
        internal static string isTrgovina_err {
            get {
                return ResourceManager.GetString("isTrgovina_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno polje!.
        /// </summary>
        internal static string lname_req {
            get {
                return ResourceManager.GetString("lname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravno korisničko ime ili lozinka!.
        /// </summary>
        internal static string login_err {
            get {
                return ResourceManager.GetString("login_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opština je obavezno polje!.
        /// </summary>
        internal static string opstina_req {
            get {
                return ResourceManager.GetString("opstina_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezno polje!.
        /// </summary>
        internal static string passw_req {
            get {
                return ResourceManager.GetString("passw_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora imati najmanje 5 karaktera!.
        /// </summary>
        internal static string passwMin_err {
            get {
                return ResourceManager.GetString("passwMin_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon je obavezno polje!.
        /// </summary>
        internal static string phone_req {
            get {
                return ResourceManager.GetString("phone_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon nije u ispravnom formatu!.
        /// </summary>
        internal static string phoneLength_err {
            get {
                return ResourceManager.GetString("phoneLength_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slika je obavezno polje!.
        /// </summary>
        internal static string picture_err {
            get {
                return ResourceManager.GetString("picture_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format za sliku!.
        /// </summary>
        internal static string pictureFormat_err {
            get {
                return ResourceManager.GetString("pictureFormat_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je zauzeto!.
        /// </summary>
        internal static string username_con {
            get {
                return ResourceManager.GetString("username_con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime je obavezno polje!.
        /// </summary>
        internal static string username_req {
            get {
                return ResourceManager.GetString("username_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime može imati najviše 20 znakova!.
        /// </summary>
        internal static string usernameMaxLength_err {
            get {
                return ResourceManager.GetString("usernameMaxLength_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisničko ime mora imati najmanje 4 karaktera!.
        /// </summary>
        internal static string usernameMinLength_err {
            get {
                return ResourceManager.GetString("usernameMinLength_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje!.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
